version: '3'

services:
  gitea:
    image: gitea/gitea:latest
    container_name: giteaforjenkins
    environment:
      - USER_UID=1000
      - USER_GID=1000
    ports:
      - "3000:3000"
      - "2222:22"
    volumes:
      - ./gitea-data:/data
    networks:
      - gitea-net

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins-data:/var/jenkins_home
    networks:
      - gitea-net

networks:
  gitea-net:
    driver: bridge

